//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSSlider
    {
        public int ID { get; set; }
        public string SliderID { get; set; }
        public string SliderType { get; set; }
        public Nullable<int> SliderOrder { get; set; }
        public string SliderImagePath { get; set; }
        public Nullable<bool> SliderStatus { get; set; }
        public string SliderTitle { get; set; }
        public string SliderDesc { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string SliderFileBase { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
