//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSEvent
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string EventCategory { get; set; }
        public string AttachFile { get; set; }
        public Nullable<int> EventOrderID { get; set; }
        public Nullable<bool> EventStatus { get; set; }
        public string Time1 { get; set; }
        public string Time2 { get; set; }
        public Nullable<int> EventPrivilege { get; set; }
        public string EventPrivilegeOption { get; set; }
        public Nullable<bool> Aproved { get; set; }
        public string AprovedBy { get; set; }
        public string EventLogic { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
        public string Category { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
