//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSGadget
    {
        public int ID { get; set; }
        public Nullable<int> GadgetID { get; set; }
        public string GadgetName { get; set; }
        public string GadgetHTML { get; set; }
        public string GadgetLanguage { get; set; }
        public string ContainID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Setting { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
