//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSPage
    {
        public int ID { get; set; }
        public string PageID { get; set; }
        public string PageTitle { get; set; }
        public string PageBody { get; set; }
        public string PageTamplateID { get; set; }
        public string PageType { get; set; }
        public string PageLanguage { get; set; }
        public Nullable<bool> Aproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string TAG { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
