//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSAnalytic
    {
        public decimal ID { get; set; }
        public string LoginUser { get; set; }
        public string RemoteIP { get; set; }
        public string Location { get; set; }
        public string RemoteHost { get; set; }
        public string ReqMethod { get; set; }
        public string Platform { get; set; }
        public string BrowserLan { get; set; }
        public string BrowserType { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<System.DateTime> CDateTime { get; set; }
        public string UserID { get; set; }
        public Nullable<int> AccessID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    }
}
