//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSInvoiceDetail
    {
        public int ID { get; set; }
        public string InvoiceNumber { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> SellRate { get; set; }
        public Nullable<decimal> BuyRate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> CTotal { get; set; }
        public Nullable<decimal> CDiscount { get; set; }
        public Nullable<decimal> CNetTotal { get; set; }
        public Nullable<decimal> DTotal { get; set; }
        public Nullable<decimal> DDiscount { get; set; }
        public Nullable<decimal> DNetTotal { get; set; }
        public string QTYFrom { get; set; }
        public Nullable<decimal> QtyS { get; set; }
        public Nullable<decimal> QtyF { get; set; }
        public string Description { get; set; }
        public string SerialNo { get; set; }
        public string House { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ReplaceInfo { get; set; }
        public Nullable<int> Damage { get; set; }
        public string DamageDesc { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> RRoom { get; set; }
        public string TransType { get; set; }
        public Nullable<double> VatPerc { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<double> Perc { get; set; }
        public Nullable<decimal> CostOfGoodSold { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public Nullable<int> TransID { get; set; }
        public Nullable<int> Box { get; set; }
        public Nullable<double> Feet { get; set; }
        public Nullable<int> Fbox { get; set; }
        public Nullable<decimal> FeetRate { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MonthFraction { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public Nullable<int> WarrantyInfo { get; set; }
        public Nullable<bool> SameClient { get; set; }
        public Nullable<int> TRoom { get; set; }
        public Nullable<int> SubSectorID { get; set; }
        public string PCID { get; set; }
        public System.Guid UIDENTITY { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public Nullable<decimal> DamageQTY { get; set; }
        public Nullable<decimal> DamageRate { get; set; }
        public Nullable<decimal> DamageAmount { get; set; }
        public Nullable<decimal> Received { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<decimal> QtyBox { get; set; }
        public Nullable<decimal> QtyLite { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
