//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSMenu
    {
        public int ID { get; set; }
        public string MenuID { get; set; }
        public string MenuParentID { get; set; }
        public string MenuType { get; set; }
        public string MenuName { get; set; }
        public string MenuDisplayName { get; set; }
        public string MenuLanguage { get; set; }
        public string MenuLink { get; set; }
        public string MenuLinkOption { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public Nullable<bool> MenuStatus { get; set; }
        public Nullable<int> MenuSerial { get; set; }
        public Nullable<int> MenuPrivilege { get; set; }
        public string MenuPrivilegeOption { get; set; }
        public string MenuIcon { get; set; }
        public string MenuContent { get; set; }
        public string MenuSlug { get; set; }
        public string MenuTitle { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
