//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSNotice
    {
        public int ID { get; set; }
        public Nullable<int> NoticeID { get; set; }
        public string NoticeName { get; set; }
        public string NoticeDescription { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public string NoticeCategory { get; set; }
        public string AttachFile { get; set; }
        public Nullable<int> NoticeOrderID { get; set; }
        public Nullable<bool> NoticeStatus { get; set; }
        public string Time1 { get; set; }
        public string Time2 { get; set; }
        public Nullable<int> NoticePrivilege { get; set; }
        public string NoticePrivilegeOption { get; set; }
        public Nullable<bool> Aproved { get; set; }
        public string AprovedBy { get; set; }
        public string NoticeLogic { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
