//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSNew
    {
        public int ID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public string NewsName { get; set; }
        public string NewsDescription { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public string NewsCategory { get; set; }
        public string AttachFile { get; set; }
        public Nullable<int> NewsOrderID { get; set; }
        public Nullable<bool> NewsStatus { get; set; }
        public string Time1 { get; set; }
        public string Time2 { get; set; }
        public Nullable<int> NewsPrivilege { get; set; }
        public string NewsPrivilegeOption { get; set; }
        public Nullable<bool> Aproved { get; set; }
        public string AprovedBy { get; set; }
        public string NewsLogic { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
