//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSAlbumDetail
    {
        public int ID { get; set; }
        public string ADID { get; set; }
        public string AID { get; set; }
        public string AlbumDetailsTitle { get; set; }
        public string AlbumDetailsDescription { get; set; }
        public Nullable<int> AlbumDetailsOrder { get; set; }
        public string AlbumDetailImagePath { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    }
}
