//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSProductInfo
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string BarCode { get; set; }
        public string Product { get; set; }
        public string ProductSlag { get; set; }
        public string Brand { get; set; }
        public string BrandInfo { get; set; }
        public string CategoryID { get; set; }
        public string Color { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> WebSellRate { get; set; }
        public Nullable<decimal> WebBuyRate { get; set; }
        public Nullable<decimal> WebSellPreRate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> FeaturedStatus { get; set; }
        public Nullable<double> InVal { get; set; }
        public Nullable<int> SubSectorID { get; set; }
        public Nullable<double> Vat { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SNID { get; set; }
        public Nullable<bool> Warranty { get; set; }
        public Nullable<System.Guid> UIDENTITY { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public string img5 { get; set; }
        public string FeatureImgPath { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
