//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspCMSInvoiceTransition
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string InvoiceNumber { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> IDate { get; set; }
        public string CSN { get; set; }
        public string Recipient { get; set; }
        public string Recipient_Address { get; set; }
        public Nullable<decimal> CTotal { get; set; }
        public Nullable<decimal> DTotal { get; set; }
        public Nullable<decimal> COther { get; set; }
        public Nullable<decimal> DOther { get; set; }
        public Nullable<decimal> CDiscount { get; set; }
        public Nullable<decimal> DDiscount { get; set; }
        public Nullable<decimal> CNetTotal { get; set; }
        public Nullable<decimal> DNetTotal { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public Nullable<decimal> NewBalance { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public string Debit_Credit { get; set; }
        public string Description { get; set; }
        public string PaymentType { get; set; }
        public string ForInvoice { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<int> SectorID { get; set; }
        public string OPID { get; set; }
        public Nullable<int> SubSectorID { get; set; }
        public string MisID { get; set; }
        public string TransType { get; set; }
        public Nullable<int> COCLeft { get; set; }
        public Nullable<int> COCRight { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<int> SNumber { get; set; }
        public Nullable<int> BehaveType { get; set; }
        public Nullable<int> TransTypeID { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> CalcDate { get; set; }
        public Nullable<System.DateTime> WarningDate { get; set; }
        public string OntheInvNo { get; set; }
        public string BondTheory { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> Approved_by { get; set; }
        public Nullable<System.DateTime> Approved_Time { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MonthFraction { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public string ConversionTo { get; set; }
        public string ConversioFrom { get; set; }
        public Nullable<int> RPID { get; set; }
        public Nullable<int> TypeOfTrans { get; set; }
        public Nullable<int> RPID1 { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> InvIDExtra { get; set; }
        public string CSN1 { get; set; }
        public string CSN2 { get; set; }
        public string CSN3 { get; set; }
        public string PCID { get; set; }
        public System.Guid UIDENTITY { get; set; }
        public string Mob { get; set; }
        public string Sex { get; set; }
        public string LabID { get; set; }
        public Nullable<decimal> Due { get; set; }
        public string TName { get; set; }
        public string TAddress { get; set; }
        public string RefDr { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
