//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MangroveSpaceEntities : DbContext
    {
        public MangroveSpaceEntities()
            : base("name=MangroveSpaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspCMSAlbum> AspCMSAlbums { get; set; }
        public virtual DbSet<AspCMSAlbumDetail> AspCMSAlbumDetails { get; set; }
        public virtual DbSet<AspCMSAllCategory> AspCMSAllCategories { get; set; }
        public virtual DbSet<AspCMSAnalytic> AspCMSAnalytics { get; set; }
        public virtual DbSet<AspCMSCategory> AspCMSCategories { get; set; }
        public virtual DbSet<AspCMSEvent> AspCMSEvents { get; set; }
        public virtual DbSet<AspCMSGadget> AspCMSGadgets { get; set; }
        public virtual DbSet<AspCMSInvoiceDetail> AspCMSInvoiceDetails { get; set; }
        public virtual DbSet<AspCMSInvoiceTransition> AspCMSInvoiceTransitions { get; set; }
        public virtual DbSet<AspCMSMail> AspCMSMails { get; set; }
        public virtual DbSet<AspCMSMemberShip> AspCMSMemberShips { get; set; }
        public virtual DbSet<AspCMSMenu> AspCMSMenus { get; set; }
        public virtual DbSet<AspCMSNew> AspCMSNews { get; set; }
        public virtual DbSet<AspCMSNotice> AspCMSNotices { get; set; }
        public virtual DbSet<AspCMSPage> AspCMSPages { get; set; }
        public virtual DbSet<AspCMSPageTemplate> AspCMSPageTemplates { get; set; }
        public virtual DbSet<AspCMSProductCategory> AspCMSProductCategories { get; set; }
        public virtual DbSet<AspCMSProductInfo> AspCMSProductInfoes { get; set; }
        public virtual DbSet<AspCMSSlider> AspCMSSliders { get; set; }
        public virtual DbSet<AspCMSTableContent> AspCMSTableContents { get; set; }
        public virtual DbSet<AspCMSTableTemplate> AspCMSTableTemplates { get; set; }
        public virtual DbSet<AspExamReGenReport> AspExamReGenReports { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspSysMenu> AspSysMenus { get; set; }
        public virtual DbSet<AspSysPrivilege> AspSysPrivileges { get; set; }
        public virtual DbSet<AspSysPrivilegeTemplate> AspSysPrivilegeTemplates { get; set; }
        public virtual DbSet<PowerPlant_BasicType> PowerPlant_BasicType { get; set; }
        public virtual DbSet<PowerPlant_Category> PowerPlant_Category { get; set; }
        public virtual DbSet<PowerPlant_Child> PowerPlant_Child { get; set; }
        public virtual DbSet<PowerPlant_ChildFuelType> PowerPlant_ChildFuelType { get; set; }
        public virtual DbSet<PowerPlant_ChildItem> PowerPlant_ChildItem { get; set; }
        public virtual DbSet<PowerPlant_Company> PowerPlant_Company { get; set; }
        public virtual DbSet<PowerPlant_CoreType> PowerPlant_CoreType { get; set; }
        public virtual DbSet<PowerPlant_Country> PowerPlant_Country { get; set; }
        public virtual DbSet<PowerPlant_FuelType> PowerPlant_FuelType { get; set; }
        public virtual DbSet<PowerPlant_General> PowerPlant_General { get; set; }
        public virtual DbSet<PowerPlant_MagnetType> PowerPlant_MagnetType { get; set; }
        public virtual DbSet<PowerPlant_Main> PowerPlant_Main { get; set; }
        public virtual DbSet<PowerPlant_SubCategory> PowerPlant_SubCategory { get; set; }
        public virtual DbSet<PowerPlant_TableControl> PowerPlant_TableControl { get; set; }
        public virtual DbSet<PowerPlant_Technical> PowerPlant_Technical { get; set; }
        public virtual DbSet<PowerPlant_Freq> PowerPlant_Freq { get; set; }
        public virtual DbSet<PowerPlant_Level> PowerPlant_Level { get; set; }
    }
}
