//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerPlant_General
    {
        public int ID { get; set; }
        public string PowerPlant_Name { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Address { get; set; }
        public string DetailsPageAddress { get; set; }
        public Nullable<int> BasicTypeID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<bool> Renewable { get; set; }
        public string State { get; set; }
        public Nullable<decimal> SiteArea { get; set; }
        public Nullable<short> OpeningYear { get; set; }
        public string Operator { get; set; }
        public string KeyFeature { get; set; }
        public string Pros { get; set; }
        public string Cons { get; set; }
        public string ImpoundedBy { get; set; }
        public Nullable<int> OwnerTypeID { get; set; }
        public string Owner { get; set; }
        public string Importance { get; set; }
        public string History { get; set; }
        public string Caution { get; set; }
        public Nullable<decimal> OverallEfficiency { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> CapacityFactor { get; set; }
        public Nullable<decimal> PowerFactor { get; set; }
        public Nullable<decimal> PowerGenerationCapacity { get; set; }
        public Nullable<decimal> VoltageRating { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<decimal> PowerRating { get; set; }
        public Nullable<decimal> AnnualEnergyGen { get; set; }
        public Nullable<int> InputEnergyID { get; set; }
        public Nullable<int> TransportID { get; set; }
        public Nullable<int> InputNatureID { get; set; }
        public string BasicComponent { get; set; }
        public string OtherComponent { get; set; }
        public string Biproduct { get; set; }
        public string OtherWaste { get; set; }
        public Nullable<int> PrimarySourceID { get; set; }
        public Nullable<int> SecondarySourceID { get; set; }
        public Nullable<int> NoOfUnit { get; set; }
        public string AboutUnit { get; set; }
        public Nullable<bool> NatGridConnected { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public Nullable<bool> Operational { get; set; }
        public string Protection { get; set; }
        public string Control { get; set; }
        public Nullable<decimal> GridVoltage { get; set; }
        public string GridDetails { get; set; }
        public Nullable<bool> GridTieInverter { get; set; }
        public string InverterDetails { get; set; }
        public Nullable<bool> PowerTransBelong { get; set; }
        public string TransDetails { get; set; }
        public Nullable<bool> SteamBoilBelong { get; set; }
        public string BoilDetails { get; set; }
        public Nullable<bool> TurbineBelong { get; set; }
        public string TurbineDetails { get; set; }
        public string InstalledBy_1 { get; set; }
        public string InstalledBy_2 { get; set; }
        public string InstalledBy_3 { get; set; }
        public string Supplier_1 { get; set; }
        public string Supplier_2 { get; set; }
        public string Supplier_3 { get; set; }
        public Nullable<decimal> ConstCost { get; set; }
        public Nullable<decimal> GenCostUnit { get; set; }
        public Nullable<decimal> SellCostUnit { get; set; }
        public string Buyer { get; set; }
        public string OtherPurpose { get; set; }
        public Nullable<int> DistFrmHuman { get; set; }
        public string NearRail { get; set; }
        public string NearBus { get; set; }
        public string NearMarket { get; set; }
        public string NearResidance { get; set; }
        public string NearHotel { get; set; }
        public string NearOther { get; set; }
        public string ComNetwork { get; set; }
        public string NearSite { get; set; }
        public Nullable<int> Climate { get; set; }
        public Nullable<int> Terrain { get; set; }
        public Nullable<int> AvgTemp { get; set; }
        public Nullable<int> AvgHumid { get; set; }
        public string Reference { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<bool> WaterTurbineBelong { get; set; }
        public string WaterTurbineDetails { get; set; }
        public Nullable<int> SeasonVariation { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    
        public virtual PowerPlant_Category PowerPlant_Category { get; set; }
        public virtual PowerPlant_Country PowerPlant_Country { get; set; }
    }
}
