//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerPlant_Main
    {
        public int ID { get; set; }
        public string Short_Description { get; set; }
        public string CountryDesc { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Power_Generation_Capacity { get; set; }
        public string Power_Rating { get; set; }
        public string Site_Area { get; set; }
        public string Commissioned_Opening { get; set; }
        public string Owner_Operator_Installed_by { get; set; }
        public string Key_Features { get; set; }
        public string Importance { get; set; }
        public string History { get; set; }
        public string Pros_Advantage { get; set; }
        public string Cons_Disadvantage { get; set; }
        public string Efficiency { get; set; }
        public string Capacity_Factor { get; set; }
        public string Technical_Specifications { get; set; }
        public string Annual_Energy_Generation { get; set; }
        public string Input_Energy_Fuel { get; set; }
        public string Fuel_Other_Transportation { get; set; }
        public string Biproduct_Waste { get; set; }
        public string Unit_s__with_Description { get; set; }
        public string Grid_Information { get; set; }
        public string Protection_Control_Others { get; set; }
        public string Inverter_Information { get; set; }
        public string Transformer_Information { get; set; }
        public string Price_Cost { get; set; }
        public string Buyer { get; set; }
        public string Nearby_Residence { get; set; }
        public string Nearby_Rail_Station { get; set; }
        public string Nearby_Bus_Stand { get; set; }
        public string Other_Transportation { get; set; }
        public string Nearby_Rest_house_Hotel { get; set; }
        public string Other_Facilities { get; set; }
        public string Nearby_Site_s_ { get; set; }
        public string Climate { get; set; }
        public string Terrain_Environment { get; set; }
        public string Caution_Warning { get; set; }
        public string Miscellaneous_Information { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Scale_Size { get; set; }
        public Nullable<int> Frequency__Hz_ { get; set; }
        public Nullable<int> Renewable_ { get; set; }
        public Nullable<int> Energy_Source_Fuel_Type { get; set; }
        public Nullable<int> Basic_Category { get; set; }
        public Nullable<int> Sub_category { get; set; }
        public Nullable<int> Popularity { get; set; }
        public Nullable<int> Power_Rating__MW_ { get; set; }
        public Nullable<int> Generated_Voltage__kV_ { get; set; }
        public Nullable<int> Establishment { get; set; }
        public Nullable<int> Efficiency____ { get; set; }
        public Nullable<int> Capacity_Factor____ { get; set; }
        public string DetailsPageAddress { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string Name { get; set; }
    
        public virtual PowerPlant_Category PowerPlant_Category { get; set; }
        public virtual PowerPlant_SubCategory PowerPlant_SubCategory { get; set; }
        public virtual PowerPlant_Country PowerPlant_Country { get; set; }
    }
}
