//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangroveSpace
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerPlant_TableControl
    {
        public int ID { get; set; }
        public string Column_Name_DB { get; set; }
        public string Column_Name_View { get; set; }
        public Nullable<int> Is_PP { get; set; }
        public string Group_Name { get; set; }
        public Nullable<int> Display_Order { get; set; }
        public Nullable<int> Is_Display { get; set; }
        public string Ref_Table { get; set; }
        public string Ref_Column { get; set; }
    }
}
